# Generated by Django 5.2 on 2025-04-17 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_interview_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='company_name',
            field=models.CharField(help_text='至少需要 3 個字', max_length=100),
        ),
        migrations.AlterField(
            model_name='interview',
            name='rating',
            field=models.PositiveSmallIntegerField(help_text='1 ~ 10 分，1 分最低，10 分最高'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interviews.interview')),
            ],
        ),
    ]
