# Generated by Django 5.2 on 2025-04-28 04:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0007_interview_favorited_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='favorited_by',
            field=models.ManyToManyField(related_name='favorite_interviews', through='interviews.FavoriteInterview', to=settings.AUTH_USER_MODEL),
        ),
    ]
